name: breezedb
description: A lightweight and easy-to-use NoSQL database for Flutter and Dart, with support for SQLite and in-memory adapters.
version: 0.0.1
repository: https://github.com/imatheus-lucas/breezeDB

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
